"""
* TencentBlueKing is pleased to support the open source community by making 蓝鲸智云-蓝鲸 PaaS 平台(BlueKing-PaaS) available.
* Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
* Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
* You may obtain a copy of the License at http://opensource.org/licenses/MIT
* Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
* an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
* specific language governing permissions and limitations under the License.
"""

"""
this command will sync the apis to bk-apigateway

the files:
- config/settings.py (the values)
- definition.yaml (the template of settings)
- resources.yaml (generated by command `generate_resource_yaml`)

reference: https://github.com/TencentBlueKing/bkpaas-python-sdk/blob/master/sdks/apigw-manager/docs/sync-apigateway-with-django.md
"""
import os

from django.conf import settings
from django.core.management import call_command
from django.core.management.base import BaseCommand


class Command(BaseCommand):
    def handle(self, *args, **kwargs):
        gateway_name = settings.BK_APIGW_NAME
        definition_file_path = os.path.join(settings.BASE_DIR, "definition.yaml")
        resources_file_path = os.path.join(settings.BASE_DIR, "resources.yaml")

        print(f"call sync_apigw_config with definition: {definition_file_path}")
        call_command(
            "sync_apigw_config",
            f"--gateway-name={gateway_name}",
            f"--file={definition_file_path}",
        )

        print(f"call sync_apigw_stage with definition: {definition_file_path}")
        call_command(
            "sync_apigw_stage",
            f"--gateway-name={gateway_name}",
            f"--file={definition_file_path}",
        )
        print(f"call sync_apigw_resources with resources: {resources_file_path}")
        call_command(
            "sync_apigw_resources",
            f"--gateway-name={gateway_name}",
            "--delete",
            f"--file={resources_file_path}",
        )

        print(
            f"call create_version_and_release_apigw with definition: {definition_file_path}, stage: {settings.BK_APIGW_DEFAULT_STAGE_NAME}"
        )
        call_command(
            "create_version_and_release_apigw",
            f"--gateway-name={gateway_name}",
            f"--file={definition_file_path}",
            f"--stage={settings.BK_APIGW_DEFAULT_STAGE_NAME}",
        )

        print(f"call grant_apigw_permissions with definition: {definition_file_path}")
        call_command(
            "grant_apigw_permissions",
            f"--gateway-name={gateway_name}",
            f"--file={definition_file_path}",
        )

        print(f"call fetch_apigw_public_key {gateway_name}")
        call_command("fetch_apigw_public_key", f"--gateway-name={gateway_name}")
