# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-13 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paas_service', '0003_auto_20200102_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInstanceConfig',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paas_app_info', jsonfield.fields.JSONField(blank=True, default=dict, verbose_name='平台应用信息')),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paas_service.ServiceInstance', verbose_name='服务实例')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
