# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-02-02 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paas_service', '0004_serviceinstanceconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinstance',
            name='plan',
            field=models.ForeignKey(help_text='当前仅当迁移的增强服务实例, 会没有 plan', null=True, on_delete=django.db.models.deletion.CASCADE, to='paas_service.Plan', verbose_name='方案'),
        ),
    ]
