# -*- coding: utf-8 -*-
# Generated by Django 3.2.12 on 2022-04-26 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paas_service', '0006_auto_20210223_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinstance',
            name='plan',
            field=models.ForeignKey(help_text='当前仅当迁移的增强服务实例, 会没有 plan', null=True, on_delete=django.db.models.deletion.SET_NULL, to='paas_service.plan', verbose_name='方案'),
        ),
        migrations.AlterField(
            model_name='serviceinstance',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paas_service.service', verbose_name='服务'),
        ),
    ]
