# Generated by Django 4.2.27 on 2026-04-09 02:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paas_service', '0009_alter_plan_unique_together_plan_tenant_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lock_key', models.CharField(max_length=64, unique=True, verbose_name='锁的 key')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='InstanceRecord',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('engine_app_name', models.CharField(max_length=64, verbose_name='引擎应用名称')),
                ('plan_id', models.UUIDField(verbose_name='方案 ID')),
                ('status', models.CharField(max_length=16, verbose_name='状态')),
                ('tenant_id', models.CharField(db_index=True, default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID')),
                ('service_instance', models.OneToOneField(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record', to='paas_service.serviceinstance', verbose_name='实例')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
