# Generated by Django 5.2.14 on 2026-08-12 09:29

import paas_service.models
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paas_service', '0010_provisionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='uuid',
            field=paas_service.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='provisionrecord',
            name='uuid',
            field=paas_service.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='uuid',
            field=paas_service.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='serviceinstance',
            name='uuid',
            field=paas_service.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='serviceinstanceconfig',
            name='uuid',
            field=paas_service.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='specdefinition',
            name='uuid',
            field=paas_service.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='uuid',
            field=paas_service.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
    ]
