# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='paas_service',
    version='1.1.3',
    python_requires='<3.11,>=3.6.2',
    author='blueking',
    author_email='blueking@tencent.com',
    packages=[
        'paas_service',
        'paas_service.auth',
        'paas_service.management',
        'paas_service.management.commands',
        'paas_service.migrations',
    ],
    package_dir={"": "."},
    package_data={},
    install_requires=['blue-krill>=1.0.15', 'django-translated-fields', 'jsonfield', 'pyjwt==1.*,>=1.6.4'],
    extras_require={
        "dev": [
            "django==1.11.20",
            "django-dynamic-fixture==2.0.0",
            "djangorestframework>=3.5.0",
            "pytest",
            "pytest-django",
            "six==1.12.0",
        ]
    },
)
