# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making
蓝鲸智云 - PaaS 平台 (BlueKing - PaaS System) available.
Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except
in compliance with the License. You may obtain a copy of the License at

    http://opensource.org/licenses/MIT

Unless required by applicable law or agreed to in writing, software distributed under
the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
either express or implied. See the License for the specific language governing permissions and
limitations under the License.

We undertake not to change the open source license (MIT license) applicable
to the current version of the project delivered to anyone in the future.
"""

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='paas_service',
    version='2.0.0',
    python_requires='<3.12,>=3.8',
    author='blueking',
    author_email='blueking@tencent.com',
    packages=[
        'paas_service',
        'paas_service.auth',
        'paas_service.management',
        'paas_service.management.commands',
        'paas_service.migrations',
    ],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        'jsonfield',
        'pyjwt>=2.4.0'
        'django-translated-fields',
        'blue-krill>=2.0.7',
        "django>=4.2.16",
        "djangorestframework>=3.15.2",
    ],
    extras_require={
        "dev": [
            "django-dynamic-fixture>=4.0.1",
            "pytest",
            "pytest-django",
            "six==1.12.0",
        ]
    },
)
