apigatewaySync:
  enabled: true
  image: "hub.bktencent.com/blueking/my-apigw-manager:latest"
  extraEnvVars:
    - name: BK_APIGW_NAME
      value: "bk-demo"
    - name: BK_APP_CODE
      value: "bk-demo"
    - name: BK_APP_SECRET
      value: "secret"
    - name: BK_API_URL_TMPL
      value: "http://bkapi.example.com/api/{api_name}"