[tox]
minversion = 3.23.0
isolated_build = True
envlist = py{311,312,313,314}-django{52}-pyjwt{2}


[gh-actions]
python =
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
extras = cryptography,drf,demo,kubernetes
deps =
    pytest>=8.3.3
    pytest-django>=4.9.0
    pytest-mock>=3.14.0
    Faker==33.0.0
    django52: django>=5.2,<6.0
    pyjwt2: pyjwt<3
commands =
    python -m pytest -v --ds demo.settings tests
