# -*- coding: utf-8 -*-
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - PaaS 平台 (BlueKing - PaaS System) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.

from functools import partial

import pytest
from cryptography.fernet import Fernet
from django.test.utils import override_settings

from blue_krill.encrypt.utils import encrypt_string
from blue_krill.secure.dj_environ import EncryptedEnviron, SecureEnv


class TestSecureEnv:
    @pytest.fixture(autouse=True)
    def set_secret_key(self):
        # FakeSecret, generated by "from cryptography.fernet import Fernet; Fernet.generate_key()"
        with override_settings(BKKRILL_ENCRYPT_SECRET_KEY="gb2MuLFVamaHC2ZAsUqIcNpfUk67MVPBO6Qa0nE5A4g="):
            yield

    def test_encrypted_value(self, monkeypatch):
        monkeypatch.setenv("DATABASE_URL", encrypt_string("mysql://u:p@localhost/foo"))
        env = SecureEnv()
        assert env.db_url() is not None
        assert env.db_url()["HOST"] == "localhost"

    def test_plain_value(self, monkeypatch):
        monkeypatch.setenv("DATABASE_URL", "mysql://u:p@localhost/foo")
        env = SecureEnv()
        with pytest.raises(ValueError, match="not encrypted"):
            env.db_url()

    def test_set_encryption_key(self, monkeypatch):
        monkeypatch.setenv("DATABASE_URL", encrypt_string("mysql://u:p@localhost/foo"))
        env = SecureEnv()
        # Set an invalid secure key
        env.set_secure_key(Fernet.generate_key())
        with pytest.raises(ValueError, match="is invalid"):
            env.db_url()

    def test_decrypt_function(self, monkeypatch):
        raw = "testing"
        monkeypatch.setenv("ENCRYPT_VALUE", encrypt_string(raw))

        class MySecureEnv(SecureEnv):
            ENVIRON_CLS = partial(EncryptedEnviron, decryptor=lambda value, key: raw)  # type: ignore

        env = MySecureEnv()
        assert env.str("ENCRYPT_VALUE") == raw
