{{- if .Values.apigatewaySync.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "bk-demo.job-name" (list . "sync-apigateway") }}
  labels: {{ include "bk-demo.labels" . | nindent 4 }}
spec:
  backoffLimit: 10
  parallelism: 1
  template:
    metadata:
      labels: {{ include "bk-demo.selector-labels" . | nindent 8 }}
        app.kubernetes.io/component: "sync-apigateway"
    spec:
      containers:
      - command:
        - bash
        args:
        - bin/sync-apigateway.sh
        image: "mirrors.tencent.com/bk-apigateway/apigw-manager:development"
        imagePullPolicy: "Always"
        name: sync-apigateway
        env:
        - name: BK_APIGW_NAME
          value: "bk-demo"
        - name: BK_APP_CODE
          value: "bk_apigateway"
        - name: BK_APP_SECRET
          value: "05dc1c40-2000-4dc4-b474-61f874ea66f7"
        - name: BK_API_URL_TMPL
          value: "http://bkapi.paas-dev-ee.woa.com/api/{api_name}"
        volumeMounts: 
        {{- range $item := .Values.apigatewaySync.configMapMounts }}
        - mountPath: "{{ $item.mountPath }}"
          name: "{{ $item.name }}"
        {{- end }}
      volumes: 
      {{- $name_prefix := include "bk-demo.name-prefix" . }}
      {{- range $item := .Values.apigatewaySync.configMapMounts }}
      - name: "{{ $item.name }}"
        configMap:
          defaultMode: 420
          name: "{{ $name_prefix }}-{{ $item.name }}"
      {{- end }}
      restartPolicy: Never
{{- end }}