spec_version: 2

release:
  # 发布版本号
  version: 1.0.0
  title: "这是一个测试"
  comment: "这是一个测试"

apigateway:
  description: "这是一个测试"
  description_en: "This is a test"
  is_public: false
  maintainers:
    - "admin"

stages:
  - name: "prod"
    description: "这是一个测试"
    description_en: "This is a test"
    backends:
      - name: "default"
        config:
          timeout: 60
          loadbalance: "roundrobin"
          hosts:
          # 网关调用后端服务的默认域名或IP，不包含Path，比如：http://api.example.com
           - host: "https://httpbin.org"
             weight: 100

# 资源文档
# 资源文档的目录格式样例如下，en 为英文文档，zh 为中文文档：
# ./
# - en
#   - anything.md
# - zh
#   - anything.md
resource_docs:
  basedir: "support-files/apidocs/"

# 主动授权，网关主动给应用，添加访问网关所有资源的权限
grant_permissions:
  - bk_app_code: "{{ settings.BK_APP_CODE }}"
    grant_dimension: "gateway"
