# Generated by Django 3.2.25 on 2025-07-30 09:53

import blue_krill.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestEncryptFieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data', blue_krill.models.fields.EncryptField(blank=True, help_text='without any explicit cipher type', null=True)),
                ('data_fernet', blue_krill.models.fields.EncryptField(blank=True, null=True)),
                ('data_sm4', blue_krill.models.fields.EncryptField(blank=True, null=True)),
            ],
        ),
    ]
