{{- if .Values.apigatewaySync.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "bk-demo.job-name" (list . "sync-apigateway") }}
  labels: {{ include "bk-demo.labels" . | nindent 4 }}
spec:
  backoffLimit: 10
  parallelism: 1
  template:
    metadata:
      labels: {{ include "bk-demo.selector-labels" . | nindent 8 }}
        app.kubernetes.io/component: "sync-apigateway"
    spec:
      containers:
      - command:
        - bash
        args:
        - bin/sync-apigateway
        image: "mirrors.example.com/blueking/my-apigw-manager:latest"
        imagePullPolicy: "Always"
        name: sync-apigateway
        env:
        - name: BK_APIGW_NAME
          value: "bk-demo"
        - name: BK_APP_CODE
          value: "bk-demo"
        - name: BK_APP_SECRET
          value: "secret"
        - name: BK_API_URL_TMPL
          value: "http://bkapi.example.com/api/{api_name}"
      restartPolicy: Never
{{- end }}